### ISSUE TITLE
Hopefully Releases will have separate JS files

### ISSUE THREAD

**Issue by xweiba** [html2canvas/html2canvas#11]
RT, the project build is too slow

**Comment by Mapaler** [comment]
用npm安装包就行，里面有单文件

**Comment by xweiba** [comment]
> 用`npm i @html2canvas/html2canvas`安装就行，里面有单文件 ![TotalCMD64_Total_Commander_(x64)11 03-_David_Attie_0278](https://private-user-images.githubusercontent.com/6565860/349973318-b69de846-8e78-4f7e-8b95-bad50a062f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTA5NTMsIm5iZiI6MTcyMTM1MDY1MywicGF0aCI6Ii82NTY1ODYwLzM0OTk3MzMxOC1iNjlkZTg0Ni04ZTc4LTRmN2UtOGI5NS1iYWQ1MGEwNjJmNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDA1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzdlZDYyNGIyYTA0MzZiMmRmOWI0OTYyNDZiZTdhNzM2ZTI1Njg3NmM0ZDRhY2NhZDYxOGViZGUyN2FhNTAwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P2WrycJZ60pDVHO02M9Ah6CU1BCzALc65hJVrYAZAQw)

好的 感谢

**Comment by yorickshan** [comment]
try to use jsdelivr ```https://cdn.jsdelivr.net/npm/html2canvas-pro@1.5.8/dist/html2canvas-pro.min.js``` or download js files at https://github.com/yorickshan/html2canvas-pro/releases
