### ISSUE TITLE
[Question] How to migrate?

### ISSUE THREAD

**Issue by Mapaler** [html2canvas/html2canvas#6]
I `npm install` first and then directly replace the previous `min.js`.

![TotalCMD64_08kE6yeffL](https://github.com/html2canvas/html2canvas/assets/6565860/038e7f8d-52f0-4f4c-8870-07c4d6db4b27)

As a result, the original code is unusable.

![firefox_yoHrEeBd6P](https://github.com/html2canvas/html2canvas/assets/6565860/d165190d-b094-4242-9a5b-cb42a2cbb573)

Or I tyr the module.
![Code_FZzldxvBqb](https://github.com/html2canvas/html2canvas/assets/6565860/ab14ef25-7192-4292-8fcc-8de24f5df529)

It also can't be used.
![firefox_hpmuFWmzAb](https://github.com/html2canvas/html2canvas/assets/6565860/8cd4a85e-598f-44e1-a054-2497ca2164bf)

### Specifications:

 * html2canvas version tested with: 1.6.2
 * Browser & version: Firefox 115.0 esr
 * Operating system: Microsoft Windows 10 [ver 10.0.19045.4593]

Please make sure you are testing with the latest [release of html2canvas](https://github.com/html2canvas/html2canvas/releases).
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- [x] You are using the latest [version](https://github.com/html2canvas/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if possible an example on [jsfiddle](https://jsfiddle.net/).

### Specifications:

 * html2canvas version tested with:
 * Browser & version:
 * Operating system:

**Comment by yorickshan** [comment]
Feel free to try using [html2canvas-pro](https://github.com/yorickshan/html2canvas-pro) v1.5.6 or the most recent version. :smile:

**Comment by Mapaler** [comment]
> Feel free to try using [html2canvas-pro](https://github.com/yorickshan/html2canvas-pro) v1.5.6 or the most recent version. 😄

I tried it a long time ago and didn't fix the problems that the original version had all the time. https://github.com/niklasvh/html2canvas/issues/2940

![firefox_智龙迷城1人队伍图制作_—_Firefox_Developer_Edition_0224](https://github.com/user-attachments/assets/d6edcb44-0628-4367-8f9d-3d0fdf59bd32)

**Comment by yorickshan** [comment]
> > Feel free to try using [html2canvas-pro](https://github.com/yorickshan/html2canvas-pro) v1.5.6 or the most recent version. 😄
> 
> I tried it a long time ago and didn't fix the problems that the original version had all the time. [niklasvh#2940](https://github.com/niklasvh/html2canvas/issues/2940)
> 
> ![firefox_智龙迷城1人队伍图制作_—_Firefox_Developer_Edition_0224](https://private-user-images.githubusercontent.com/6565860/348585864-d6edcb44-0628-4367-8f9d-3d0fdf59bd32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTE5MjcsIm5iZiI6MTcyMTAxMTYyNywicGF0aCI6Ii82NTY1ODYwLzM0ODU4NTg2NC1kNmVkY2I0NC0wNjI4LTQzNjctOGY5ZC0zZDBmZGY1OWJkMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDI0NzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjg5ZTg3ZTgwMzUxY2NhNGIxYjg0ZjNjOTNmZjYwODVkOTkyMjdhZGY4N2ZjZWM0ZTRmZDBlYjI3MWUzOTc5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7uoiVCPeyzAyJnOCNpxviH2DSQOs3nQDk40haqEQU6c)

问题的原因感觉应该是 html2canvas 不支持 box-shadow：https://github.com/niklasvh/html2canvas/blob/master/docs/features.md#unsupported-css-properties，然后 html2canvas-pro 目前也没有支持

**Comment by Mapaler** [comment]
> 问题的原因感觉应该是 html2canvas 不支持 box-shadow：https://github.com/niklasvh/html2canvas/blob/master/docs/features.md#unsupported-css-properties 然后 html2canvas-pro 目前也没有支持

如果不支持可以不绘制，绘制一个黑条也挺麻烦的。
可以用中文的话我就去反馈其他BUG

**Comment by yorickshan** [comment]
> > 问题的原因感觉应该是 html2canvas 不支持 box-shadow：https://github.com/niklasvh/html2canvas/blob/master/docs/features.md#unsupported-css-properties 然后 html2canvas-pro 目前也没有支持
> 
> 如果不支持可以不绘制，绘制一个黑条也挺麻烦的。 可以用中文的话我就去反馈其他BUG

可以的，反馈可以带上诉求和建议，以及你在该问题已经找到的相关线索和做过的尝试

**Comment by yorickshan** [comment]
> > 问题的原因感觉应该是 html2canvas 不支持 box-shadow：https://github.com/niklasvh/html2canvas/blob/master/docs/features.md#unsupported-css-properties 然后 html2canvas-pro 目前也没有支持
> 
> 如果不支持可以不绘制，绘制一个黑条也挺麻烦的。 可以用中文的话我就去反馈其他BUG

当然建议还是尽量用英文，这样其他人看到也能一起想方案解决，现在翻译软件 GPT 之类的也很方便

**Comment by Mapaler** [comment]
1.6.3 可以用了

**Comment by Zefling** [comment]
Sorry, I don't read Chinese.

**Comment by Mapaler** [comment]
> Sorry, I don't read Chinese.

Sorry I say, Today's 1.6.3 update is already working.
